// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NNAContext;

namespace NNAContext.Migrations
{
    [DbContext(typeof(NNA_Context))]
    [Migration("20221206194359_addNewEstatus")]
    partial class addNewEstatus
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.15")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Modelos.Acceso.Roles", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Estatus")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("73e08b06-a8c8-4960-9708-d77d4f938f0c"),
                            Descripcion = "ADMINISTRADOR DEL SISTEMA, TIENE ACCESO A TODO",
                            Estatus = true,
                            Nombre = "ADMINISTRADOR"
                        },
                        new
                        {
                            Id = new Guid("49ecfee1-61f3-4e38-a28a-fe74c1bcb02c"),
                            Descripcion = "ENCARGADO DE VER Y ASIGNAR LAS DENUNCIAS RECIBIDAS",
                            Estatus = true,
                            Nombre = "FISCALIA ESPECIALIZADA"
                        },
                        new
                        {
                            Id = new Guid("aec4592c-fe97-47d0-97d2-1933fd2da4b9"),
                            Descripcion = "PUEDE VER TODAS LAS DENUNCIAS DE SUS AGENTES DEL MINISTERIO PUBLICO",
                            Estatus = true,
                            Nombre = "TITULAR DE UNIDAD"
                        },
                        new
                        {
                            Id = new Guid("6f1be536-c224-4f31-914e-c9d00cce1eb9"),
                            Descripcion = "AGENTE DEL MINISTERIO PUBLICO",
                            Estatus = true,
                            Nombre = "AGENTE DEL MINISTERIO PUBLICO"
                        });
                });

            modelBuilder.Entity("Modelos.Acceso.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ApellidoMaterno")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApellidoPaterno")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contraseña")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Correo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Estatus")
                        .HasColumnType("bit");

                    b.Property<Guid>("IdFiscalia")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdRol")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdUnidad")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuario");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1e28ad5c-8897-4f35-846e-beaede16b3b0"),
                            Contraseña = "123qwe",
                            Correo = "root@fiscalia.puebla.gob.mx",
                            Estatus = true,
                            IdFiscalia = new Guid("f54fd0d9-be76-4c38-b7ed-edeb6f4c9939"),
                            IdRol = new Guid("73e08b06-a8c8-4960-9708-d77d4f938f0c"),
                            IdUnidad = new Guid("1d02eda0-a6b8-4c08-9888-e61db604ecf0"),
                            Nombre = "Administrador"
                        });
                });

            modelBuilder.Entity("Modelos.Actions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Actions", "Catalogo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Alguien me pegó y me lastimó"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Alguien me tocó o me hizo tocar su cuerpo"
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Alguien me grita o me dice cosas malas"
                        },
                        new
                        {
                            Id = 4,
                            Descripcion = "Alguien me manda a trabajar"
                        });
                });

            modelBuilder.Entity("Modelos.Caso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Caso", "Catalogo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Niños y Niñas"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Adolescentes"
                        });
                });

            modelBuilder.Entity("Modelos.Denuncia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Asignada")
                        .HasColumnType("bit");

                    b.Property<string>("Casa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Edad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EdadRecord")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Escuela")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Estatus")
                        .HasColumnType("int");

                    b.Property<string>("Evento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EventoRecord")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Expediente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("Folio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IdAction")
                        .HasColumnType("int");

                    b.Property<int>("IdCaso")
                        .HasColumnType("int");

                    b.Property<int>("IdEmotion")
                        .HasColumnType("int");

                    b.Property<Guid>("IdFiscalia")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdMp")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Latitud")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Longitud")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Municipio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreRecord")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParentsName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParentsRecord")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Photo")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("PlaceName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SomeDataRecord")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Denuncia");
                });

            modelBuilder.Entity("Modelos.Emotion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Emotion", "Catalogo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "BIEN"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "MAL"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "ENOJADO"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "TRISTE"
                        },
                        new
                        {
                            Id = 5,
                            Nombre = "PREOCUPADO"
                        });
                });

            modelBuilder.Entity("Modelos.Estatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Estatus");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "SIN ATENDER",
                            Status = true
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "ARCHIVO",
                            Status = true
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "EAT",
                            Status = true
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "CDI",
                            Status = true
                        });
                });

            modelBuilder.Entity("Modelos.Fiscalias", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Acronimo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Estatus")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Fiscalias", "Catalogo");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f54fd0d9-be76-4c38-b7ed-edeb6f4c9939"),
                            Acronimo = "NONE",
                            Estatus = true,
                            Nombre = " NONE"
                        },
                        new
                        {
                            Id = new Guid("30df8b24-2f67-49c1-922d-0b1fb219aef9"),
                            Acronimo = "FEIDVGM",
                            Estatus = true,
                            Nombre = "Fiscalía Especializada en Investigación de Delitos de Violencia de Género Contra las Mujeres"
                        });
                });

            modelBuilder.Entity("Modelos.MP", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AltaSistema")
                        .HasColumnType("datetime2");

                    b.Property<string>("ApellidoMaterno")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApellidoPaterno")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Estatus")
                        .HasColumnType("bit");

                    b.Property<Guid>("IdUnidad")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MP");
                });

            modelBuilder.Entity("Modelos.Unidades", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Estatus")
                        .HasColumnType("bit");

                    b.Property<Guid>("IdFiscalia")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Unidades", "Catalogo");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1d02eda0-a6b8-4c08-9888-e61db604ecf0"),
                            Estatus = true,
                            IdFiscalia = new Guid("f54fd0d9-be76-4c38-b7ed-edeb6f4c9939"),
                            Nombre = " NONE"
                        },
                        new
                        {
                            Id = new Guid("e13f9fdb-f883-4a0f-b1d5-66ce02249944"),
                            Estatus = true,
                            IdFiscalia = new Guid("30df8b24-2f67-49c1-922d-0b1fb219aef9"),
                            Nombre = "UNIDAD ESPECIALIZADA EN INVESTIGACION DE DELITOS SEXUALES Y CIBERACOSO"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
