// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NNAContext;

namespace NNAContext.Migrations
{
    [DbContext(typeof(NNA_Context))]
    [Migration("20221212222955_AddEstatus_IdMunicipio")]
    partial class AddEstatus_IdMunicipio
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.15")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Modelos.Acceso.Roles", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Estatus")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("73e08b06-a8c8-4960-9708-d77d4f938f0c"),
                            Descripcion = "ADMINISTRADOR DEL SISTEMA, TIENE ACCESO A TODO",
                            Estatus = true,
                            Nombre = "ADMINISTRADOR"
                        },
                        new
                        {
                            Id = new Guid("49ecfee1-61f3-4e38-a28a-fe74c1bcb02c"),
                            Descripcion = "ENCARGADO DE VER Y ASIGNAR LAS DENUNCIAS RECIBIDAS",
                            Estatus = true,
                            Nombre = "FISCALIA ESPECIALIZADA"
                        },
                        new
                        {
                            Id = new Guid("aec4592c-fe97-47d0-97d2-1933fd2da4b9"),
                            Descripcion = "PUEDE VER TODAS LAS DENUNCIAS DE SUS AGENTES DEL MINISTERIO PUBLICO",
                            Estatus = true,
                            Nombre = "TITULAR DE UNIDAD"
                        },
                        new
                        {
                            Id = new Guid("6f1be536-c224-4f31-914e-c9d00cce1eb9"),
                            Descripcion = "AGENTE DEL MINISTERIO PUBLICO",
                            Estatus = true,
                            Nombre = "AGENTE DEL MINISTERIO PUBLICO"
                        });
                });

            modelBuilder.Entity("Modelos.Acceso.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ApellidoMaterno")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApellidoPaterno")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contraseña")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Correo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Estatus")
                        .HasColumnType("bit");

                    b.Property<Guid>("IdFiscalia")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdRol")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdUnidad")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuario");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1e28ad5c-8897-4f35-846e-beaede16b3b0"),
                            Contraseña = "123qwe",
                            Correo = "root@fiscalia.puebla.gob.mx",
                            Estatus = true,
                            IdFiscalia = new Guid("f54fd0d9-be76-4c38-b7ed-edeb6f4c9939"),
                            IdRol = new Guid("73e08b06-a8c8-4960-9708-d77d4f938f0c"),
                            IdUnidad = new Guid("1d02eda0-a6b8-4c08-9888-e61db604ecf0"),
                            Nombre = "Administrador"
                        });
                });

            modelBuilder.Entity("Modelos.Actions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Actions", "Catalogo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Alguien me pegó y me lastimó"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Alguien me tocó o me hizo tocar su cuerpo"
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Alguien me grita o me dice cosas malas"
                        },
                        new
                        {
                            Id = 4,
                            Descripcion = "Alguien me manda a trabajar"
                        });
                });

            modelBuilder.Entity("Modelos.Caso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Caso", "Catalogo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Niños y Niñas"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Adolescentes"
                        });
                });

            modelBuilder.Entity("Modelos.Denuncia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Asignada")
                        .HasColumnType("bit");

                    b.Property<string>("Casa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Edad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EdadRecord")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Escuela")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Estatus")
                        .HasColumnType("int");

                    b.Property<string>("Evento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EventoRecord")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Expediente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("Folio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IdAction")
                        .HasColumnType("int");

                    b.Property<int>("IdCaso")
                        .HasColumnType("int");

                    b.Property<int>("IdEmotion")
                        .HasColumnType("int");

                    b.Property<Guid>("IdFiscalia")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdMp")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("IdMunicipio")
                        .HasColumnType("int");

                    b.Property<string>("Latitud")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Longitud")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Municipio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreRecord")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParentsName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParentsRecord")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Photo")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("PlaceName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SomeDataRecord")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Denuncia");
                });

            modelBuilder.Entity("Modelos.Emotion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Emotion", "Catalogo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "BIEN"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "MAL"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "ENOJADO"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "TRISTE"
                        },
                        new
                        {
                            Id = 5,
                            Nombre = "PREOCUPADO"
                        });
                });

            modelBuilder.Entity("Modelos.Estatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Estatus");
                });

            modelBuilder.Entity("Modelos.Fiscalias", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Acronimo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Estatus")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Fiscalias", "Catalogo");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f54fd0d9-be76-4c38-b7ed-edeb6f4c9939"),
                            Acronimo = "NONE",
                            Estatus = true,
                            Nombre = " NONE"
                        },
                        new
                        {
                            Id = new Guid("30df8b24-2f67-49c1-922d-0b1fb219aef9"),
                            Acronimo = "FEIDVGM",
                            Estatus = true,
                            Nombre = "Fiscalía Especializada en Investigación de Delitos de Violencia de Género Contra las Mujeres"
                        });
                });

            modelBuilder.Entity("Modelos.MP", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AltaSistema")
                        .HasColumnType("datetime2");

                    b.Property<string>("ApellidoMaterno")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApellidoPaterno")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Estatus")
                        .HasColumnType("bit");

                    b.Property<Guid>("IdUnidad")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MP");
                });

            modelBuilder.Entity("Modelos.Municipio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Municipio", "Catalogo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Acajete"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Acateno"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Acatlán"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Acatzingo"
                        },
                        new
                        {
                            Id = 5,
                            Nombre = "Acteopan"
                        },
                        new
                        {
                            Id = 6,
                            Nombre = "Ahuacatlán"
                        },
                        new
                        {
                            Id = 7,
                            Nombre = "Ahuatlán"
                        },
                        new
                        {
                            Id = 8,
                            Nombre = "Ahuazotepec"
                        },
                        new
                        {
                            Id = 9,
                            Nombre = "Ahuehuetitla"
                        },
                        new
                        {
                            Id = 10,
                            Nombre = "Ajalpan"
                        },
                        new
                        {
                            Id = 11,
                            Nombre = "Albino Zertuche"
                        },
                        new
                        {
                            Id = 12,
                            Nombre = "Aljojuca"
                        },
                        new
                        {
                            Id = 13,
                            Nombre = "Altepexi"
                        },
                        new
                        {
                            Id = 14,
                            Nombre = "Amixtlán"
                        },
                        new
                        {
                            Id = 15,
                            Nombre = "Amozoc"
                        },
                        new
                        {
                            Id = 16,
                            Nombre = "Aquixtla"
                        },
                        new
                        {
                            Id = 17,
                            Nombre = "Atempan"
                        },
                        new
                        {
                            Id = 18,
                            Nombre = "Atexcal"
                        },
                        new
                        {
                            Id = 19,
                            Nombre = "Atlixco"
                        },
                        new
                        {
                            Id = 20,
                            Nombre = "Atoyatempan"
                        },
                        new
                        {
                            Id = 21,
                            Nombre = "Atzala"
                        },
                        new
                        {
                            Id = 22,
                            Nombre = "Atzitzihuacán"
                        },
                        new
                        {
                            Id = 23,
                            Nombre = "Atzitzintla"
                        },
                        new
                        {
                            Id = 24,
                            Nombre = "Axutla"
                        },
                        new
                        {
                            Id = 25,
                            Nombre = "Ayotoxco de Guerrero"
                        },
                        new
                        {
                            Id = 26,
                            Nombre = "Calpan"
                        },
                        new
                        {
                            Id = 27,
                            Nombre = "Caltepec"
                        },
                        new
                        {
                            Id = 28,
                            Nombre = "Camocuautla"
                        },
                        new
                        {
                            Id = 29,
                            Nombre = "Caxhuacan"
                        },
                        new
                        {
                            Id = 30,
                            Nombre = "Coatepec"
                        },
                        new
                        {
                            Id = 31,
                            Nombre = "Coatzingo"
                        },
                        new
                        {
                            Id = 32,
                            Nombre = "Cohetzala"
                        },
                        new
                        {
                            Id = 33,
                            Nombre = "Cohuecan"
                        },
                        new
                        {
                            Id = 34,
                            Nombre = "Coronango"
                        },
                        new
                        {
                            Id = 35,
                            Nombre = "Coxcatlán"
                        },
                        new
                        {
                            Id = 36,
                            Nombre = "Coyomeapan"
                        },
                        new
                        {
                            Id = 37,
                            Nombre = "Coyotepec"
                        },
                        new
                        {
                            Id = 38,
                            Nombre = "Cuapiaxtla de Madero"
                        },
                        new
                        {
                            Id = 39,
                            Nombre = "Cuautempan"
                        },
                        new
                        {
                            Id = 40,
                            Nombre = "Cuautinchán"
                        },
                        new
                        {
                            Id = 41,
                            Nombre = "Cuautlancingo"
                        },
                        new
                        {
                            Id = 42,
                            Nombre = "Cuayuca de Andrade"
                        },
                        new
                        {
                            Id = 43,
                            Nombre = "Cuetzalan del Progreso"
                        },
                        new
                        {
                            Id = 44,
                            Nombre = "Cuyoaco"
                        },
                        new
                        {
                            Id = 45,
                            Nombre = "Chalchicomula de Sesma"
                        },
                        new
                        {
                            Id = 46,
                            Nombre = "Chapulco"
                        },
                        new
                        {
                            Id = 47,
                            Nombre = "Chiautla"
                        },
                        new
                        {
                            Id = 48,
                            Nombre = "Chiautzingo"
                        },
                        new
                        {
                            Id = 49,
                            Nombre = "Chiconcuautla"
                        },
                        new
                        {
                            Id = 50,
                            Nombre = "Chichiquila"
                        },
                        new
                        {
                            Id = 51,
                            Nombre = "Chietla"
                        },
                        new
                        {
                            Id = 52,
                            Nombre = "Chigmecatitlán"
                        },
                        new
                        {
                            Id = 53,
                            Nombre = "Chignahuapan"
                        },
                        new
                        {
                            Id = 54,
                            Nombre = "Chignautla"
                        },
                        new
                        {
                            Id = 55,
                            Nombre = "Chila"
                        },
                        new
                        {
                            Id = 56,
                            Nombre = "Chila de la Sal"
                        },
                        new
                        {
                            Id = 57,
                            Nombre = "Honey"
                        },
                        new
                        {
                            Id = 58,
                            Nombre = "Chilchotla"
                        },
                        new
                        {
                            Id = 59,
                            Nombre = "Chinantla"
                        },
                        new
                        {
                            Id = 60,
                            Nombre = "Domingo Arenas"
                        },
                        new
                        {
                            Id = 61,
                            Nombre = "Eloxochitlán"
                        },
                        new
                        {
                            Id = 62,
                            Nombre = "Epatlán"
                        },
                        new
                        {
                            Id = 63,
                            Nombre = "Esperanza"
                        },
                        new
                        {
                            Id = 64,
                            Nombre = "Francisco Z. Mena"
                        },
                        new
                        {
                            Id = 65,
                            Nombre = "General Felipe Ángeles"
                        },
                        new
                        {
                            Id = 66,
                            Nombre = "Guadalupe"
                        },
                        new
                        {
                            Id = 67,
                            Nombre = "Guadalupe Victoria"
                        },
                        new
                        {
                            Id = 68,
                            Nombre = "Hermenegildo Galeana"
                        },
                        new
                        {
                            Id = 69,
                            Nombre = "Huaquechula"
                        },
                        new
                        {
                            Id = 70,
                            Nombre = "Huatlatlauca"
                        },
                        new
                        {
                            Id = 71,
                            Nombre = "Huauchinango"
                        },
                        new
                        {
                            Id = 72,
                            Nombre = "Huehuetla"
                        },
                        new
                        {
                            Id = 73,
                            Nombre = "Huehuetlán el Chico"
                        },
                        new
                        {
                            Id = 74,
                            Nombre = "Huejotzingo"
                        },
                        new
                        {
                            Id = 75,
                            Nombre = "Hueyapan"
                        },
                        new
                        {
                            Id = 76,
                            Nombre = "Hueytamalco"
                        },
                        new
                        {
                            Id = 77,
                            Nombre = "Hueytlalpan"
                        },
                        new
                        {
                            Id = 78,
                            Nombre = "Huitzilan de Serdán"
                        },
                        new
                        {
                            Id = 79,
                            Nombre = "Huitziltepec"
                        },
                        new
                        {
                            Id = 80,
                            Nombre = "Atlequizayan"
                        },
                        new
                        {
                            Id = 81,
                            Nombre = "Ixcamilpa de Guerrero"
                        },
                        new
                        {
                            Id = 82,
                            Nombre = "Ixcaquixtla"
                        },
                        new
                        {
                            Id = 83,
                            Nombre = "Ixtacamaxtitlán"
                        },
                        new
                        {
                            Id = 84,
                            Nombre = "Ixtepec"
                        },
                        new
                        {
                            Id = 85,
                            Nombre = "Izúcar de Matamoros"
                        },
                        new
                        {
                            Id = 86,
                            Nombre = "Jalpan"
                        },
                        new
                        {
                            Id = 87,
                            Nombre = "Jolalpan"
                        },
                        new
                        {
                            Id = 88,
                            Nombre = "Jonotla"
                        },
                        new
                        {
                            Id = 89,
                            Nombre = "Jopala"
                        },
                        new
                        {
                            Id = 90,
                            Nombre = "Juan C. Bonilla"
                        },
                        new
                        {
                            Id = 91,
                            Nombre = "Juan Galindo"
                        },
                        new
                        {
                            Id = 92,
                            Nombre = "Juan N. Méndez"
                        },
                        new
                        {
                            Id = 93,
                            Nombre = "Lafragua"
                        },
                        new
                        {
                            Id = 94,
                            Nombre = "Libres"
                        },
                        new
                        {
                            Id = 95,
                            Nombre = "La Magdalena Tlatlauquitepec"
                        },
                        new
                        {
                            Id = 96,
                            Nombre = "Mazapiltepec de Juárez"
                        },
                        new
                        {
                            Id = 97,
                            Nombre = "Mixtla"
                        },
                        new
                        {
                            Id = 98,
                            Nombre = "Molcaxac"
                        },
                        new
                        {
                            Id = 99,
                            Nombre = "Cañada Morelos"
                        },
                        new
                        {
                            Id = 100,
                            Nombre = "Naupan"
                        },
                        new
                        {
                            Id = 101,
                            Nombre = "Nauzontla"
                        },
                        new
                        {
                            Id = 102,
                            Nombre = "Nealtican"
                        },
                        new
                        {
                            Id = 103,
                            Nombre = "Nicolás Bravo"
                        },
                        new
                        {
                            Id = 104,
                            Nombre = "Nopalucan"
                        },
                        new
                        {
                            Id = 105,
                            Nombre = "Ocotepec"
                        },
                        new
                        {
                            Id = 106,
                            Nombre = "Ocoyucan"
                        },
                        new
                        {
                            Id = 107,
                            Nombre = "Olintla"
                        },
                        new
                        {
                            Id = 108,
                            Nombre = "Oriental"
                        },
                        new
                        {
                            Id = 109,
                            Nombre = "Pahuatlán"
                        },
                        new
                        {
                            Id = 110,
                            Nombre = "Palmar de Bravo"
                        },
                        new
                        {
                            Id = 111,
                            Nombre = "Pantepec"
                        },
                        new
                        {
                            Id = 112,
                            Nombre = "Petlalcingo"
                        },
                        new
                        {
                            Id = 113,
                            Nombre = "Piaxtla"
                        },
                        new
                        {
                            Id = 114,
                            Nombre = "Puebla"
                        },
                        new
                        {
                            Id = 115,
                            Nombre = "Quecholac"
                        },
                        new
                        {
                            Id = 116,
                            Nombre = "Quimixtlán"
                        },
                        new
                        {
                            Id = 117,
                            Nombre = "Rafael Lara Grajales"
                        },
                        new
                        {
                            Id = 118,
                            Nombre = "Los Reyes de Juárez"
                        },
                        new
                        {
                            Id = 119,
                            Nombre = "San Andrés Cholula"
                        },
                        new
                        {
                            Id = 120,
                            Nombre = "San Antonio Cañada"
                        },
                        new
                        {
                            Id = 121,
                            Nombre = "San Diego la Mesa Tochimiltzingo"
                        },
                        new
                        {
                            Id = 122,
                            Nombre = "San Felipe Teotlalcingo"
                        },
                        new
                        {
                            Id = 123,
                            Nombre = "San Felipe Tepatlán"
                        },
                        new
                        {
                            Id = 124,
                            Nombre = "San Gabriel Chilac"
                        },
                        new
                        {
                            Id = 125,
                            Nombre = "San Gregorio Atzompa"
                        },
                        new
                        {
                            Id = 126,
                            Nombre = "San Jerónimo Tecuanipan"
                        },
                        new
                        {
                            Id = 127,
                            Nombre = "San Jerónimo Xayacatlán"
                        },
                        new
                        {
                            Id = 128,
                            Nombre = "San José Chiapa"
                        },
                        new
                        {
                            Id = 129,
                            Nombre = "San José Miahuatlán"
                        },
                        new
                        {
                            Id = 130,
                            Nombre = "San Juan Atenco"
                        },
                        new
                        {
                            Id = 131,
                            Nombre = "San Juan Atzompa"
                        },
                        new
                        {
                            Id = 132,
                            Nombre = "San Martín Texmelucan"
                        },
                        new
                        {
                            Id = 133,
                            Nombre = "San Martín Totoltepec"
                        },
                        new
                        {
                            Id = 134,
                            Nombre = "San Matías Tlalancaleca"
                        },
                        new
                        {
                            Id = 135,
                            Nombre = "San Miguel Ixitlán"
                        },
                        new
                        {
                            Id = 136,
                            Nombre = "San Miguel Xoxtla"
                        },
                        new
                        {
                            Id = 137,
                            Nombre = "San Nicolás Buenos Aires"
                        },
                        new
                        {
                            Id = 138,
                            Nombre = "San Nicolás de los Ranchos"
                        },
                        new
                        {
                            Id = 139,
                            Nombre = "San Pablo Anicano"
                        },
                        new
                        {
                            Id = 140,
                            Nombre = "San Pedro Cholula"
                        },
                        new
                        {
                            Id = 141,
                            Nombre = "San Pedro Yeloixtlahuaca"
                        },
                        new
                        {
                            Id = 142,
                            Nombre = "San Salvador el Seco"
                        },
                        new
                        {
                            Id = 143,
                            Nombre = "San Salvador el Verde"
                        },
                        new
                        {
                            Id = 144,
                            Nombre = "San Salvador Huixcolotla"
                        },
                        new
                        {
                            Id = 145,
                            Nombre = "San Sebastián Tlacotepec"
                        },
                        new
                        {
                            Id = 146,
                            Nombre = "Santa Catarina Tlaltempan"
                        },
                        new
                        {
                            Id = 147,
                            Nombre = "Santa Inés Ahuatempan"
                        },
                        new
                        {
                            Id = 148,
                            Nombre = "Santa Isabel Cholula"
                        },
                        new
                        {
                            Id = 149,
                            Nombre = "Santiago Miahuatlán"
                        },
                        new
                        {
                            Id = 150,
                            Nombre = "Huehuetlán el Grande"
                        },
                        new
                        {
                            Id = 151,
                            Nombre = "Santo Tomás Hueyotlipan"
                        },
                        new
                        {
                            Id = 152,
                            Nombre = "Soltepec"
                        },
                        new
                        {
                            Id = 153,
                            Nombre = "Tecali de Herrera"
                        },
                        new
                        {
                            Id = 154,
                            Nombre = "Tecamachalco"
                        },
                        new
                        {
                            Id = 155,
                            Nombre = "Tecomatlán"
                        },
                        new
                        {
                            Id = 156,
                            Nombre = "Tehuacán"
                        },
                        new
                        {
                            Id = 157,
                            Nombre = "Tehuitzingo"
                        },
                        new
                        {
                            Id = 158,
                            Nombre = "Tenampulco"
                        },
                        new
                        {
                            Id = 159,
                            Nombre = "Teopantlán"
                        },
                        new
                        {
                            Id = 160,
                            Nombre = "Teotlalco"
                        },
                        new
                        {
                            Id = 161,
                            Nombre = "Tepanco de López"
                        },
                        new
                        {
                            Id = 162,
                            Nombre = "Tepango de Rodríguez"
                        },
                        new
                        {
                            Id = 163,
                            Nombre = "Tepatlaxco de Hidalgo"
                        },
                        new
                        {
                            Id = 164,
                            Nombre = "Tepeaca"
                        },
                        new
                        {
                            Id = 165,
                            Nombre = "Tepemaxalco"
                        },
                        new
                        {
                            Id = 166,
                            Nombre = "Tepeojuma"
                        },
                        new
                        {
                            Id = 167,
                            Nombre = "Tepetzintla"
                        },
                        new
                        {
                            Id = 168,
                            Nombre = "Tepexco"
                        },
                        new
                        {
                            Id = 169,
                            Nombre = "Tepexi de Rodríguez"
                        },
                        new
                        {
                            Id = 170,
                            Nombre = "Tepeyahualco"
                        },
                        new
                        {
                            Id = 171,
                            Nombre = "Tepeyahualco de Cuauhtémoc"
                        },
                        new
                        {
                            Id = 172,
                            Nombre = "Tetela de Ocampo"
                        },
                        new
                        {
                            Id = 173,
                            Nombre = "Teteles de Ávila Castillo"
                        },
                        new
                        {
                            Id = 174,
                            Nombre = "Teziutlán"
                        },
                        new
                        {
                            Id = 175,
                            Nombre = "Tianguismanalco"
                        },
                        new
                        {
                            Id = 176,
                            Nombre = "Tilapa"
                        },
                        new
                        {
                            Id = 177,
                            Nombre = "Tlacotepec de Benito Juárez"
                        },
                        new
                        {
                            Id = 178,
                            Nombre = "Tlacuilotepec"
                        },
                        new
                        {
                            Id = 179,
                            Nombre = "Tlachichuca"
                        },
                        new
                        {
                            Id = 180,
                            Nombre = "Tlahuapan"
                        },
                        new
                        {
                            Id = 181,
                            Nombre = "Tlaltenango"
                        },
                        new
                        {
                            Id = 182,
                            Nombre = "Tlanepantla"
                        },
                        new
                        {
                            Id = 183,
                            Nombre = "Tlaola"
                        },
                        new
                        {
                            Id = 184,
                            Nombre = "Tlapacoya"
                        },
                        new
                        {
                            Id = 185,
                            Nombre = "Tlapanalá"
                        },
                        new
                        {
                            Id = 186,
                            Nombre = "Tlatlauquitepec"
                        },
                        new
                        {
                            Id = 187,
                            Nombre = "Tlaxco"
                        },
                        new
                        {
                            Id = 188,
                            Nombre = "Tochimilco"
                        },
                        new
                        {
                            Id = 189,
                            Nombre = "Tochtepec"
                        },
                        new
                        {
                            Id = 190,
                            Nombre = "Totoltepec de Guerrero"
                        },
                        new
                        {
                            Id = 191,
                            Nombre = "Tulcingo"
                        },
                        new
                        {
                            Id = 192,
                            Nombre = "Tuzamapan de Galeana"
                        },
                        new
                        {
                            Id = 193,
                            Nombre = "Tzicatlacoyan"
                        },
                        new
                        {
                            Id = 194,
                            Nombre = "Venustiano Carranza"
                        },
                        new
                        {
                            Id = 195,
                            Nombre = "Vicente Guerrero"
                        },
                        new
                        {
                            Id = 196,
                            Nombre = "Xayacatlán de Bravo"
                        },
                        new
                        {
                            Id = 197,
                            Nombre = "Xicotepec"
                        },
                        new
                        {
                            Id = 198,
                            Nombre = "Xicotlán"
                        },
                        new
                        {
                            Id = 199,
                            Nombre = "Xiutetelco"
                        },
                        new
                        {
                            Id = 200,
                            Nombre = "Xochiapulco"
                        },
                        new
                        {
                            Id = 201,
                            Nombre = "Xochiltepec"
                        },
                        new
                        {
                            Id = 202,
                            Nombre = "Xochitlán de Vicente Suárez"
                        },
                        new
                        {
                            Id = 203,
                            Nombre = "Xochitlán Todos Santos"
                        },
                        new
                        {
                            Id = 204,
                            Nombre = "Yaonáhuac"
                        },
                        new
                        {
                            Id = 205,
                            Nombre = "Yehualtepec"
                        },
                        new
                        {
                            Id = 206,
                            Nombre = "Zacapala"
                        },
                        new
                        {
                            Id = 207,
                            Nombre = "Zacapoaxtla"
                        },
                        new
                        {
                            Id = 208,
                            Nombre = "Zacatlán"
                        },
                        new
                        {
                            Id = 209,
                            Nombre = "Zapotitlán"
                        },
                        new
                        {
                            Id = 210,
                            Nombre = "Zapotitlán de Méndez"
                        },
                        new
                        {
                            Id = 211,
                            Nombre = "Zaragoza"
                        },
                        new
                        {
                            Id = 212,
                            Nombre = "Zautla"
                        },
                        new
                        {
                            Id = 213,
                            Nombre = "Zihuateutla"
                        },
                        new
                        {
                            Id = 214,
                            Nombre = "Zinacatepec"
                        },
                        new
                        {
                            Id = 215,
                            Nombre = "Zongozotla"
                        },
                        new
                        {
                            Id = 216,
                            Nombre = "Zoquiapan"
                        },
                        new
                        {
                            Id = 217,
                            Nombre = "Zoquitlán"
                        });
                });

            modelBuilder.Entity("Modelos.Unidades", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Estatus")
                        .HasColumnType("bit");

                    b.Property<Guid>("IdFiscalia")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Unidades", "Catalogo");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1d02eda0-a6b8-4c08-9888-e61db604ecf0"),
                            Estatus = true,
                            IdFiscalia = new Guid("f54fd0d9-be76-4c38-b7ed-edeb6f4c9939"),
                            Nombre = " NONE"
                        },
                        new
                        {
                            Id = new Guid("e13f9fdb-f883-4a0f-b1d5-66ce02249944"),
                            Estatus = true,
                            IdFiscalia = new Guid("30df8b24-2f67-49c1-922d-0b1fb219aef9"),
                            Nombre = "UNIDAD ESPECIALIZADA EN INVESTIGACION DE DELITOS SEXUALES Y CIBERACOSO"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
