// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NNAContext;

namespace NNAContext.Migrations
{
    [DbContext(typeof(NNA_Context))]
    [Migration("20221118153956_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.15")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Modelos.Acceso.Roles", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Estatus")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("49ecfee1-61f3-4e38-a28a-fe74c1bcb02c"),
                            Descripcion = "ENCARGADO DE ASIGNAR LAS DENUNCIAS RECIBIDAS",
                            Estatus = true,
                            Nombre = "ASESOR"
                        },
                        new
                        {
                            Id = new Guid("6f1be536-c224-4f31-914e-c9d00cce1eb9"),
                            Descripcion = "AGENTE DEL MINISTERIO PUBLICO",
                            Estatus = true,
                            Nombre = "MP"
                        });
                });

            modelBuilder.Entity("Modelos.Acceso.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Contraseña")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Correo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Estatus")
                        .HasColumnType("bit");

                    b.Property<Guid>("IdRol")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Usuario");

                    b.HasData(
                        new
                        {
                            Id = new Guid("542ac5f1-da0f-4454-9700-defa2d131b9d"),
                            Contraseña = "123qwe",
                            Correo = "marco_antonio.cantero@fiscalia.puebla.gob.mx",
                            Estatus = true,
                            IdRol = new Guid("49ecfee1-61f3-4e38-a28a-fe74c1bcb02c")
                        });
                });

            modelBuilder.Entity("Modelos.Actions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Actions", "Catalogo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Alguien me pegó y me lastimó"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Alguien me tocó o me hizo tocar su cuerpo"
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Alguien me grita o me dice cosas malas"
                        },
                        new
                        {
                            Id = 4,
                            Descripcion = "Alguien me manda a trabajar"
                        });
                });

            modelBuilder.Entity("Modelos.Caso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Caso", "Catalogo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Niños y Niñas"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Adolescentes"
                        });
                });

            modelBuilder.Entity("Modelos.Denuncia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Asignada")
                        .HasColumnType("bit");

                    b.Property<string>("Casa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Edad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EdadRecord")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Escuela")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Evento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EventoRecord")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("Folio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IdAction")
                        .HasColumnType("int");

                    b.Property<int>("IdCaso")
                        .HasColumnType("int");

                    b.Property<int>("IdEmotion")
                        .HasColumnType("int");

                    b.Property<string>("Latitud")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Longitud")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Municipio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreRecord")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroDenuncia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParentsName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParentsRecord")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Photo")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("PlaceName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SomeDataRecord")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Denuncia");
                });

            modelBuilder.Entity("Modelos.Emotion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Emotion", "Catalogo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "BIEN"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "MAL"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "ENOJADO"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "TRISTE"
                        },
                        new
                        {
                            Id = 5,
                            Nombre = "PREOCUPADO"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
